export const OBTENER_PROSPECTOS = 'OBTENER_PROSPECTOS';
export const AGREGAR_PROSPECTO = 'AGREGAR_PROSPECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROSPECTO_ACTUAL = 'PROSPECTO_ACTUAL';
export const ESTADO_PROSPECTO = 'ESTADO_PROSPECTO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';